[aliases]
# yarn
y = "yarn"
yi = "yarn install"
ya = "yarn add"
yad = "yarn add -D"
yb = "yarn build"
# pnpm
p = "pnpm"
pi = "pnpm install"
pa = "pnpm add"
pad = "pnpm add -D"
pb = "pnpm build"
px = "pnpm exec"
# eza
ls = "eza"
l = "eza -al"
ll = "eza -l"
lt = "eza -T"
# create-x
cvite = "create-x --url https://github.com/nomyfan/templates/tree/main/vite-react-ts --name"
# bat
b = "bat"
bp = "bat -p"
# git
gds = "git diff --staged"
grmc = "git rm -r --cached"
gsn = "git show --name-only"
'gc.' = "git commit -m ."
gcls = "git clone --depth 1" # shallow git clone
# cargo
c = "cargo"
cb = "cargo build"
cbc = "cargo bench"
cr = "cargo run"
ct = "cargo test"
cl = "cargo clippy"
ci = "cargo install"
cbi = "cargo binstall"
ccr = "cargo criterion"
# rg
rgi = "rg -i"
# misc
test-ci = "git commit --allow-empty -m 'test ci' && git push"
up-codex = "npm i -g @openai/codex"
up-cc = "npm i -g @anthropic-ai/claude-code"

[aliases.cls]
zsh = "clear"

[aliases.opgh]
zsh = "node $HOME/.ss/JavaScript/opx.mjs gh"
powershell = "node (Join-Path $HOME .ss JavaScript opx.mjs gh)"

[aliases.opn]
zsh = "node $HOME/.ss/JavaScript/opx.mjs npm"
powershell = "node (Join-Path $HOME .ss JavaScript opx.mjs npm)"

[aliases.ghu]
zsh = "node $HOME/.ss/JavaScript/ghu.mjs"
powershell = "node (Join-Path $HOME .ss JavaScript ghu.mjs)"

[aliases.rmrf]
zsh = "rm -rf"
powershell = "Remove-Item -Recurse -Force"

[aliases.cwd]
zsh = "if [[ $(uname) == 'Darwin' ]]; then pwd | pbcopy; else pwd | xclip; fi" # Tested on macOS only
powershell = "Get-Location | Set-Clipboard"

[aliases.snm]
zsh = "node $HOME/.ss/JavaScript/sync-npmmirror.mjs"
powershell = "node (Join-Path $HOME .ss JavaScript sync-npmmirror.mjs)"

[aliases.b64hex]
zsh = "node $HOME/.ss/JavaScript/b64hex.mjs"
powershell = "node (Join-Path $HOME .ss JavaScript b64hex.mjs)"
# zsh = "base64 -d | hexdump -v -e '1/1 \\\"%02x\\\"'"

