[skills.commit-please]
source_url = "https://github.com/nomyfan/dotfiles/tree/skills/skills/commit-please"
slug = "nomyfan/dotfiles"
path = "skills/commit-please"
sha = "041a42198f68dcc6e0d980694840be9ce2c83b74"
checksum = "sha256:2c5436cfcf54a28a1308d3ac0609269671394bdf31d2dca72595ea9dd044c232"

[skills.mcp-skill-creator]
source_url = "https://github.com/nomyfan/dotfiles/tree/skills/skills/mcp-skill-creator"
slug = "nomyfan/dotfiles"
path = "skills/mcp-skill-creator"
sha = "6d0c2399eabdd5ff4b829133409e4b0b7813fc44"
checksum = "sha256:bff261da84534a4268904a5335cb0492672606cc703d55e67c8d96fc96423d7d"

[skills.skill-creator]
source_url = "https://github.com/anthropics/skills/tree/main/skills/skill-creator"
slug = "anthropics/skills"
path = "skills/skill-creator"
sha = "7bd8fc459f09f0e14dcc2adbb4a5a58e60ea755c"
checksum = "sha256:983170c54ebd674cfd33cc0d3269e0cc2ec36163abfb0d292e36e4dfec9ff9cc"
