[skills.mcp-skill-creator]
source_url = "https://github.com/nomyfan/dotfiles/tree/c4ce38c52f8f569dc4f7e475672a804fae4a44f1/skillx/mcp-skill-creator"
checksum = "sha256:bff261da84534a4268904a5335cb0492672606cc703d55e67c8d96fc96423d7d"
