[package]
name = "xbin"
version = "0.1.0"
edition = "2024"

[dependencies]
open = "5"
clap = "4"
which = "5"
sysinfo = "0.30.5"


[[bin]]
name = "open"
path = "src/open.rs"

[[bin]]
name = "which"
path = "src/which.rs"
